AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trip Cortex - AI-powered corporate travel booking system

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment
  
  ClerkSecretKeyArn:
    Type: String
    Description: ARN of Clerk secret key in Secrets Manager
    Default: ''

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        AWS_REGION: !Ref AWS::Region
        POWERTOOLS_SERVICE_NAME: trip-cortex
        LOG_LEVEL: INFO

Resources:
  # Placeholder - Resources will be added in Story 1.4
  # This section will contain:
  # - DynamoDB tables (Bookings, Connections, AuditLog)
  # - S3 buckets (PolicyDocuments, NovaActArtifacts)
  # - Lambda functions
  # - Step Functions state machine
  # - API Gateway WebSocket API
  # - IAM roles and policies

Outputs:
  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName
  
  Environment:
    Description: Deployment environment
    Value: !Ref Environment
  
  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
