AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trip Cortex - AI-powered corporate travel booking system

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment
  
  ClerkSecretKeyArn:
    Type: String
    Description: ARN of Clerk secret key in Secrets Manager
    Default: ''

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        AWS_REGION: !Ref AWS::Region
        POWERTOOLS_SERVICE_NAME: trip-cortex
        LOG_LEVEL: INFO
        BOOKINGS_TABLE: !Ref BookingsTable
        CONNECTIONS_TABLE: !Ref ConnectionsTable
        AUDIT_LOG_TABLE: !Ref AuditLogTable

Conditions:
  IsNotDev: !Not [!Equals [!Ref Environment, dev]]

Resources:

  # ── DynamoDB Tables ──────────────────────────────────────────────────────────

  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-bookings"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: employeeId
          AttributeType: S
        - AttributeName: bookingId
          AttributeType: S
      KeySchema:
        - AttributeName: employeeId
          KeyType: HASH
        - AttributeName: bookingId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsNotDev, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-connections"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  AuditLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-audit-log"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: auditId
          AttributeType: S
        - AttributeName: employeeId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
        - AttributeName: auditId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: employeeId-timestamp-index
          KeySchema:
            - AttributeName: employeeId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

Outputs:
  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName
  
  Environment:
    Description: Deployment environment
    Value: !Ref Environment
  
  Region:
    Description: AWS Region
    Value: !Ref AWS::Region

  BookingsTableName:
    Description: Bookings DynamoDB table name
    Value: !Ref BookingsTable
    Export:
      Name: !Sub "${AWS::StackName}-BookingsTableName"

  BookingsTableArn:
    Description: Bookings DynamoDB table ARN
    Value: !GetAtt BookingsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BookingsTableArn"

  ConnectionsTableName:
    Description: Connections DynamoDB table name
    Value: !Ref ConnectionsTable
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTableName"

  ConnectionsTableArn:
    Description: Connections DynamoDB table ARN
    Value: !GetAtt ConnectionsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTableArn"

  AuditLogTableName:
    Description: AuditLog DynamoDB table name
    Value: !Ref AuditLogTable
    Export:
      Name: !Sub "${AWS::StackName}-AuditLogTableName"

  AuditLogTableArn:
    Description: AuditLog DynamoDB table ARN
    Value: !GetAtt AuditLogTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AuditLogTableArn"
