AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trip Cortex - AI-powered corporate travel booking system

Parameters:

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

  ClerkSecretKeyArn:
    Type: String
    Description: ARN of Clerk secret key in Secrets Manager
    Default: ''

  WebSocketApiId:
    Type: String
    Description: API Gateway WebSocket API ID (set in Story 1.7)
    Default: placeholder

Resources:

  # ── DynamoDB Tables ──────────────────────────────────────────────────────────

  TablesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infra/tables.yaml
      Parameters:
        Environment: !Ref Environment
        StackPrefix: !Ref AWS::StackName

  # ── S3 Buckets ───────────────────────────────────────────────────────────────

  StorageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infra/storage.yaml
      Parameters:
        Environment: !Ref Environment
        StackPrefix: !Ref AWS::StackName

  # ── Step Functions ───────────────────────────────────────────────────────────

  WorkflowStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infra/workflow.yaml
      Parameters:
        Environment: !Ref Environment
        StackPrefix: !Ref AWS::StackName

  # ── Lambda Functions ─────────────────────────────────────────────────────────

  FunctionsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infra/functions.yaml
      Parameters:
        Environment: !Ref Environment
        BookingsTableArn: !GetAtt TablesStack.Outputs.BookingsTableArn
        ConnectionsTableArn: !GetAtt TablesStack.Outputs.ConnectionsTableArn
        AuditLogTableArn: !GetAtt TablesStack.Outputs.AuditLogTableArn
        PolicyDocumentsBucketArn: !GetAtt StorageStack.Outputs.PolicyDocumentsBucketArn
        BookingWorkflowArn: !GetAtt WorkflowStack.Outputs.BookingWorkflowArn
        WebSocketApiId: !Ref WebSocketApiId
        BookingsTableName: !GetAtt TablesStack.Outputs.BookingsTableName
        ConnectionsTableName: !GetAtt TablesStack.Outputs.ConnectionsTableName
        AuditLogTableName: !GetAtt TablesStack.Outputs.AuditLogTableName
        PolicyDocumentsBucketName: !GetAtt StorageStack.Outputs.PolicyDocumentsBucketName
        NovaActArtifactsBucketName: !GetAtt StorageStack.Outputs.NovaActArtifactsBucketName

Outputs:
  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName

  Environment:
    Description: Deployment environment
    Value: !Ref Environment

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region

  BookingsTableName:
    Value: !GetAtt TablesStack.Outputs.BookingsTableName
    Export:
      Name: !Sub "${AWS::StackName}-BookingsTableName"

  BookingsTableArn:
    Value: !GetAtt TablesStack.Outputs.BookingsTableArn
    Export:
      Name: !Sub "${AWS::StackName}-BookingsTableArn"

  ConnectionsTableName:
    Value: !GetAtt TablesStack.Outputs.ConnectionsTableName
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTableName"

  ConnectionsTableArn:
    Value: !GetAtt TablesStack.Outputs.ConnectionsTableArn
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTableArn"

  AuditLogTableName:
    Value: !GetAtt TablesStack.Outputs.AuditLogTableName
    Export:
      Name: !Sub "${AWS::StackName}-AuditLogTableName"

  AuditLogTableArn:
    Value: !GetAtt TablesStack.Outputs.AuditLogTableArn
    Export:
      Name: !Sub "${AWS::StackName}-AuditLogTableArn"

  PolicyDocumentsBucketName:
    Value: !GetAtt StorageStack.Outputs.PolicyDocumentsBucketName
    Export:
      Name: !Sub "${AWS::StackName}-PolicyDocumentsBucketName"

  PolicyDocumentsBucketArn:
    Value: !GetAtt StorageStack.Outputs.PolicyDocumentsBucketArn
    Export:
      Name: !Sub "${AWS::StackName}-PolicyDocumentsBucketArn"

  NovaActArtifactsBucketName:
    Value: !GetAtt StorageStack.Outputs.NovaActArtifactsBucketName
    Export:
      Name: !Sub "${AWS::StackName}-NovaActArtifactsBucketName"

  NovaActArtifactsBucketArn:
    Value: !GetAtt StorageStack.Outputs.NovaActArtifactsBucketArn
    Export:
      Name: !Sub "${AWS::StackName}-NovaActArtifactsBucketArn"

  BookingWorkflowArn:
    Value: !GetAtt WorkflowStack.Outputs.BookingWorkflowArn
    Export:
      Name: !Sub "${AWS::StackName}-BookingWorkflowArn"

  ConnectFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.ConnectFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-ConnectFunctionArn"

  DisconnectFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.DisconnectFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-DisconnectFunctionArn"

  BookingRequestFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.BookingRequestFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-BookingRequestFunctionArn"

  EmbedAndRetrieveFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.EmbedAndRetrieveFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-EmbedAndRetrieveFunctionArn"

  ReasonAndPlanFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.ReasonAndPlanFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-ReasonAndPlanFunctionArn"

  ValidatePlanFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.ValidatePlanFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-ValidatePlanFunctionArn"

  ResponseSenderFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.ResponseSenderFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-ResponseSenderFunctionArn"

  HeartbeatFunctionArn:
    Value: !GetAtt FunctionsStack.Outputs.HeartbeatFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-HeartbeatFunctionArn"
