AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trip Cortex - DynamoDB Tables

Parameters:
  Environment:
    Type: String
  StackPrefix:
    Type: String

Conditions:
  IsNotDev: !Not [!Equals [!Ref Environment, dev]]

Resources:

  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackPrefix}-bookings"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: employeeId
          AttributeType: S
        - AttributeName: bookingId
          AttributeType: S
      KeySchema:
        - AttributeName: employeeId
          KeyType: HASH
        - AttributeName: bookingId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsNotDev, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackPrefix}-connections"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  AuditLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackPrefix}-audit-log"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: auditId
          AttributeType: S
        - AttributeName: employeeId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
        - AttributeName: auditId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: employeeId-timestamp-index
          KeySchema:
            - AttributeName: employeeId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

Outputs:
  BookingsTableName:
    Value: !Ref BookingsTable
  BookingsTableArn:
    Value: !GetAtt BookingsTable.Arn
  ConnectionsTableName:
    Value: !Ref ConnectionsTable
  ConnectionsTableArn:
    Value: !GetAtt ConnectionsTable.Arn
  AuditLogTableName:
    Value: !Ref AuditLogTable
  AuditLogTableArn:
    Value: !GetAtt AuditLogTable.Arn
