/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as ConfirmationBookingIdRouteImport } from './routes/confirmation.$bookingId'
import { Route as BookFlightIdRouteImport } from './routes/book.$flightId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationBookingIdRoute = ConfirmationBookingIdRouteImport.update({
  id: '/confirmation/$bookingId',
  path: '/confirmation/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFlightIdRoute = BookFlightIdRouteImport.update({
  id: '/book/$flightId',
  path: '/book/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/deals': typeof DealsRoute
  '/search': typeof SearchRoute
  '/book/$flightId': typeof BookFlightIdRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/login/$': typeof LoginSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/deals': typeof DealsRoute
  '/search': typeof SearchRoute
  '/book/$flightId': typeof BookFlightIdRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/login/$': typeof LoginSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/deals': typeof DealsRoute
  '/search': typeof SearchRoute
  '/book/$flightId': typeof BookFlightIdRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/login/$': typeof LoginSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/deals'
    | '/search'
    | '/book/$flightId'
    | '/confirmation/$bookingId'
    | '/login/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/deals'
    | '/search'
    | '/book/$flightId'
    | '/confirmation/$bookingId'
    | '/login/$'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/deals'
    | '/search'
    | '/book/$flightId'
    | '/confirmation/$bookingId'
    | '/login/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  DealsRoute: typeof DealsRoute
  SearchRoute: typeof SearchRoute
  BookFlightIdRoute: typeof BookFlightIdRoute
  ConfirmationBookingIdRoute: typeof ConfirmationBookingIdRoute
  LoginSplatRoute: typeof LoginSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$bookingId': {
      id: '/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/confirmation/$bookingId'
      preLoaderRoute: typeof ConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$flightId': {
      id: '/book/$flightId'
      path: '/book/$flightId'
      fullPath: '/book/$flightId'
      preLoaderRoute: typeof BookFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  DealsRoute: DealsRoute,
  SearchRoute: SearchRoute,
  BookFlightIdRoute: BookFlightIdRoute,
  ConfirmationBookingIdRoute: ConfirmationBookingIdRoute,
  LoginSplatRoute: LoginSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
