AWSTemplateFormatVersion: '2010-09-09'
Description: Trip Cortex - Aurora Serverless v2 cluster with pgvector support

Parameters:

  Environment:
    Type: String
    AllowedValues: [dev, staging, prod]

  StackPrefix:
    Type: String

  PrivateSubnetIds:
    Type: String
    Description: Comma-delimited list of private subnet IDs

  AuroraSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:

  # ── Secrets Manager ───────────────────────────────────────────────────────────

  AuroraSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${StackPrefix}-aurora-secret"
      Description: Aurora master credentials for Trip Cortex
      GenerateSecretString:
        SecretStringTemplate: '{"username": "tripcortex"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  # ── DB Subnet Group ───────────────────────────────────────────────────────────

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for Aurora Serverless v2
      SubnetIds: !Split [",", !Ref PrivateSubnetIds]
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-aurora-subnet-group"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  # ── Aurora Serverless v2 Cluster ──────────────────────────────────────────────

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: !If [IsProd, Snapshot, Delete]
    UpdateReplacePolicy: !If [IsProd, Snapshot, Delete]
    Properties:
      Engine: aurora-postgresql
      EngineVersion: '15.10'
      DatabaseName: tripcortex
      MasterUsername: !Sub '{{resolve:secretsmanager:${AuroraSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${AuroraSecret}:SecretString:password}}'
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 2
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref AuroraSecurityGroupId
      StorageEncrypted: true
      BackupRetentionPeriod: !If [IsProd, 7, 1]
      EnableCloudwatchLogsExports:
        - postgresql
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-aurora"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  # ── Aurora Writer Instance ────────────────────────────────────────────────────

  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref AuroraCluster
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-aurora-instance-1"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  # ── Secret Target Attachment (enriches secret with host/port/dbname) ──────────

  AuroraSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref AuroraSecret
      TargetId: !Ref AuroraCluster
      TargetType: AWS::RDS::DBCluster

Outputs:

  AuroraClusterArn:
    Description: Aurora cluster ARN
    Value: !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AuroraCluster}"

  AuroraClusterEndpoint:
    Description: Aurora cluster writer endpoint
    Value: !GetAtt AuroraCluster.Endpoint.Address

  AuroraSecretArn:
    Description: Secrets Manager secret ARN for Aurora credentials
    Value: !Ref AuroraSecret

  AuroraPort:
    Description: Aurora port
    Value: !GetAtt AuroraCluster.Endpoint.Port

  AuroraDatabaseName:
    Description: Aurora database name
    Value: tripcortex
