AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trip Cortex - S3 Buckets

Parameters:
  Environment:
    Type: String
  StackPrefix:
    Type: String

Resources:

  PolicyDocumentsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${StackPrefix}-policy-docs-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: BdaOutputToIA
            Status: Enabled
            Prefix: bda-output/
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

  NovaActArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackPrefix}-nova-act-artifacts-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireScreenshots
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: trip-cortex
        - Key: ManagedBy
          Value: sam

Outputs:
  PolicyDocumentsBucketName:
    Value: !Ref PolicyDocumentsBucket
  PolicyDocumentsBucketArn:
    Value: !GetAtt PolicyDocumentsBucket.Arn
  NovaActArtifactsBucketName:
    Value: !Ref NovaActArtifactsBucket
  NovaActArtifactsBucketArn:
    Value: !GetAtt NovaActArtifactsBucket.Arn
