"""initial_schema_policies_and_chunks

Revision ID: 2f59c70e0b61
Revises:
Create Date: 2026-02-27 17:36:43.999340

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f59c70e0b61"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension — not detectable by autogenerate
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_s3_uri", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("bda_project_arn", sa.String(length=512), nullable=True),
        sa.Column("bda_invocation_arn", sa.String(length=512), nullable=True),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("total_chunks", sa.Integer(), server_default="0", nullable=True),
        sa.Column("uploaded_by", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("status IN ('pending', 'processing', 'ready', 'failed')", name="chk_policies_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_policies_status", "policies", ["status"], unique=False)
    op.create_index("idx_policies_uploaded_by", "policies", ["uploaded_by"], unique=False)
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("section_title", sa.String(length=255), nullable=True),
        sa.Column("reading_order", sa.Integer(), nullable=True),
        sa.Column("bda_entity_id", sa.String(length=255), nullable=True),
        sa.Column("bda_entity_subtype", sa.String(length=50), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("content_type IN ('text', 'table', 'figure')", name="chk_content_type"),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_policy_chunks_content_type", "policy_chunks", ["content_type"], unique=False)
    op.create_index("idx_policy_chunks_policy_id", "policy_chunks", ["policy_id"], unique=False)

    # HNSW vector index — not detectable by autogenerate
    op.execute("""
        CREATE INDEX idx_policy_chunks_embedding
        ON policy_chunks USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_policy_chunks_embedding", table_name="policy_chunks")
    op.drop_index("idx_policy_chunks_policy_id", table_name="policy_chunks")
    op.drop_index("idx_policy_chunks_content_type", table_name="policy_chunks")
    op.drop_table("policy_chunks")
    op.drop_index("idx_policies_uploaded_by", table_name="policies")
    op.drop_index("idx_policies_status", table_name="policies")
    op.drop_table("policies")
    # ### end Alembic commands ###
